version: '3.9'
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: cinema-postgres
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_DEFAULT_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
