version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: cinema-postgres
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_DEFAULT_PORT}'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - '${MINIO_PORT}:${MINIO_PORT}'
      - '${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}'
    env_file:
      - .env
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
    driver: local
